### ISSUE TITLE
Packages Not Found in conda env create

### ISSUE THREAD

**Issue by Qifan94** [pearsonlab/BinaryStim#1]
D:\GitHub\BinaryStim>conda env create --file environment.yml
Collecting package metadata: done
Solving environment: failed

ResolvePackageNotFound:
  - matplotlib-base==3.1.3=py36hef1b27d_0
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - glib==2.63.1=h3eb4bd4_1
  - sip==4.19.8=py36hf484d3e_0
  - mkl-service==2.3.0=py36he904b0f_0
  - libedit==3.1.20181209=hc058e9b_0
  - icu==58.2=he6710b0_3
  - gstreamer==1.14.0=hb31296c_0
  - ncurses==6.2=he6710b0_1
  - mkl_random==1.1.1=py36h0573a6f_0
  - qt==5.9.7=h5867ecd_1
  - libpng==1.6.37=hbc83047_0
  - intel-openmp==2020.1=217
  - gst-plugins-base==1.14.0=hbbd80ab_1
  - mkl==2020.1=217
  - tk==8.6.8=hbc83047_0
  - openssl==1.1.1g=h7b6447c_0
  - cupy==6.0.0=py36h062aff8_0
  - sqlite==3.31.1=h62c20be_1
  - fontconfig==2.13.0=h9420a91_0
  - tornado==6.0.4=py36h7b6447c_1
  - ld_impl_linux-64==2.33.1=h53a641e_7
  - expat==2.2.6=he6710b0_0
  - fastrlock==0.4=py36he6710b0_0
  - libxcb==1.13=h1bed415_1
  - libxml2==2.9.9=hea5a465_1
  - mkl_fft==1.0.15=py36ha843d7b_0
  - xz==5.2.5=h7b6447c_0
  - dbus==1.13.14=hb2f20db_0
  - libgcc-ng==9.1.0=hdf63c60_0
  - zlib==1.2.11=h7b6447c_3
  - nccl==1.3.4=cuda8.0_1
  - jpeg==9b=h024ee3a_2
  - libffi==3.3=he6710b0_1
  - libgfortran-ng==7.3.0=hdf63c60_0
  - numpy-base==1.18.1=py36hde5b4d6_1
  - pyqt==5.9.2=py36h05f1152_2
  - cudnn==7.1.3=cuda8.0_0
  - pcre==8.43=he6710b0_0
  - freetype==2.9.1=h8a8886c_1
  - numpy==1.18.1=py36h4f9e942_0
  - python==3.6.10=h7579374_2
  - kiwisolver==1.2.0=py36hfd86e86_0
  - readline==8.0=h7b6447c_0
  - libuuid==1.0.3=h1bed415_2

**Comment by Qifan94** [comment]
![image](https://user-images.githubusercontent.com/26030147/102057609-20372c00-3e29-11eb-854d-b562e4473492.png)

**Comment by draelos** [comment]
Unfortunately conda is sometimes unable to resolve specific package versions, especially across platforms. Our environment file was tested on Ubuntu, which is likely why you're having an issue.
Really, since we only use numpy, cupy, and matplotlib, it should be easy enough to create the environment and just install those 3 packages for your system, and conda can figure out the appropriate versions itself. 

So you would (1) create a new conda environment and activate it, then (2) conda install numpy cupy matplotlib.

Let me know if you're still having issues with it after that!
